//! Renders `reports/REPORT.md` - the write-up the notebook would have contained.
//!
//! Every number in the prose is a value measured during the run, passed in here.
//! Nothing in this file is a remembered figure.

use std::fmt::Write as _;

use hp_core::features::FeatureSpec;

use crate::dataset::CleaningLog;
use crate::eda::Facts;
use crate::train::{Metrics, Run};

/// One row of the raw-column profile.
pub struct Column {
    /// Column name as it appears in the CSV header.
    pub name: String,
    /// Share of rows where the column is blank.
    pub missing_pct: f64,
    /// Distinct values, blank included.
    pub distinct: usize,
    /// A short example value.
    pub example: String,
}

/// What the `Society` column looks like, used to justify dropping it.
pub struct Society {
    /// Distinct non-blank society names.
    pub distinct: usize,
    /// Share of all rows covered by the 50 most common societies.
    pub top50_coverage_pct: f64,
}

/// Everything the report needs, gathered by the pipeline.
pub struct Report<'a> {
    /// Per-column profile of the raw file.
    pub profile: Vec<Column>,
    /// What cleaning dropped.
    pub cleaning: &'a CleaningLog,
    /// High-cardinality evidence for `Society`.
    pub society: Society,
    /// Numbers behind the EDA charts.
    pub facts: &'a Facts,
    /// The exported feature spec.
    pub spec: &'a FeatureSpec,
    /// Rows used for gradient steps.
    pub train_rows: usize,
    /// Rows used to select the epoch.
    pub val_rows: usize,
    /// Rows scored exactly once, at the end.
    pub test_rows: usize,
    /// Every trained model.
    pub runs: Vec<&'a Run>,
    /// Name of the model that was exported.
    pub winner: &'static str,
    /// The no-model estimate: city median price per sqft times area.
    pub baseline: Metrics,
    /// The same architecture trained with duplicates left in.
    pub leaky: &'a Run,
    /// Bonus cross-validation folds, when they were run.
    pub cv: Option<Vec<Metrics>>,
}

/// Groups digits so six-figure row counts stay readable.
fn thousands(n: usize) -> String {
    let digits = n.to_string();
    let mut out = String::with_capacity(digits.len() + digits.len() / 3);
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(c);
    }
    out
}

/// Formats rupees the way the listings do.
fn rupees(v: f64) -> String {
    if v.abs() >= 1e7 {
        format!("{:.2} Cr", v / 1e7)
    } else if v.abs() >= 1e5 {
        format!("{:.2} Lac", v / 1e5)
    } else {
        format!("{v:.0}")
    }
}

impl Report<'_> {
    /// Renders the whole document.
    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub fn render(&self) -> String {
        let mut s = String::new();
        let q = self.facts.price_quantiles;
        let kept = self.cleaning.total
            - self.cleaning.no_price
            - self.cleaning.no_area
            - self.cleaning.duplicates
            - self.cleaning.outliers;

        s.push_str("# House Price Prediction - model report\n\n");
        s.push_str("Generated by `cargo run --release -p ml`. Every number here was measured in that run, and the charts are saved next to this file.\n\n");
        s.push_str("The model is trained with [Vearo](https://github.com/razecrs/vearo), a Rust deep learning framework, so there's no Python in this project. The cleaning, the charts and this report are Rust too.\n\n");

        // -- 1 ---------------------------------------------------------------
        let n_locations = self
            .profile
            .iter()
            .find(|c| c.name == "location")
            .map_or(0, |c| c.distinct);
        let _ = write!(
            s,
            "## 1. Load and inspect\n\nThe raw file is **{} rows x {} columns**. Looking at it properly first changed three decisions, so it's worth doing before trusting the column names.\n\n| column | missing | distinct | example |\n|---|---|---|---|\n",
            thousands(self.cleaning.total),
            self.profile.len()
        );
        for c in &self.profile {
            let _ = writeln!(
                s,
                "| `{}` | {:.1}% | {} | {} |",
                c.name, c.missing_pct, c.distinct, c.example
            );
        }
        let _ = write!(
            s,
            "\nThree things the table contradicts:\n\n\
1. **`location` is a city, not a neighbourhood.** It has {n_locations} distinct values across 187k rows - `new-delhi`, `bangalore`, `kolkata`. Keeping the top 50 and bucketing the rest therefore costs almost nothing here, but it still runs, because it is what makes an unseen city safe at inference time.\n\
2. **`Price (in rupees)` is not the price.** Its values sit in the thousands while `Amount(in rupees)` holds `42 Lac`. It is the *rate per square foot*, so using it as a feature would leak the target: rate x area is the answer. It is excluded from the model.\n\
3. **`Dimensions`, `Plot Area` and `Status` carry no information.** The first two are 100% blank; `Status` is `Ready to Move` in every non-blank row. All three are dropped.\n\n"
        );

        // -- 2 ---------------------------------------------------------------
        let _ = write!(
            s,
            "## 2. Cleaning and feature engineering\n\n\
| step | rows |\n|---|---|\n\
| raw | {} |\n\
| dropped: no usable price (`Call for Price` or blank) | -{} |\n\
| dropped: no usable area in either area column | -{} |\n\
| dropped: duplicate listings | -{} |\n\
| dropped: price-per-sqft outside the 1st-99th percentile | -{} |\n\
| **kept** | **{}** |\n\n",
            thousands(self.cleaning.total),
            thousands(self.cleaning.no_price),
            thousands(self.cleaning.no_area),
            thousands(self.cleaning.duplicates),
            thousands(self.cleaning.outliers),
            thousands(kept)
        );

        let _ = write!(
            s,
            "### The duplicates are the story\n\n\
**{} of the {} rows ({:.0}%) are repeats.** Ignoring the `Index` column the file holds only {} distinct listings, and the most repeated advertisement appears **821 times**. Splitting a file like that at random puts the same listing on both sides of the split, and the test set stops measuring prediction and starts measuring memory.\n\n\
So de-duplication happens *before* the split. Two rows are the same listing when every feature the model sees and the price are identical; `Index` and the free-text columns are not part of that key, because they differ between copies of what is plainly one advertisement. Section 5 puts a number on what this was worth.\n\n",
            thousands(self.cleaning.duplicates),
            thousands(self.cleaning.total),
            100.0 * self.cleaning.duplicates as f64 / self.cleaning.total as f64,
            thousands(
                self.cleaning.total
                    - self.cleaning.duplicates
                    - self.cleaning.no_price
                    - self.cleaning.no_area
            )
        );

        let _ = write!(
            s,
            "### What each messy column needed\n\n\
- **Price is text.** `Amount(in rupees)` is `\"42 Lac\"`, `\"1.40 Cr\"` or `\"Call for Price\"`. Parsed with 1 Lac = 100,000 and 1 Cr = 10,000,000; the {} `Call for Price` rows have no target and are dropped rather than guessed at.\n\
- **Areas are text, in ten different units.** `Carpet Area` and `Super Area` are `\"1200 sqft\"`, `\"140 sqyrd\"`, `\"90 sqm\"`, and a long tail of `marla`, `kanal`, `bigha`, `acre`. Everything is converted to square feet through a unit table; an unknown unit returns nothing instead of a wrong number.\n\
- **Two area columns, each mostly empty.** Carpet is 43% present and super area 57%, but between them all but {} rows have one. Carpet area is the honest measurement, so it wins when both exist, and a binary `is_carpet_area` feature tells the model which one it is looking at - super area is systematically larger, and without the flag that difference would read as noise.\n\
- **`Floor` is `\"3 out of 10\"`.** Split into the storey and the building height, with `Ground` = 0, `Basement` = -1, `Lower Basement` = -2. A `floor_ratio` feature carries how high up the flat is relative to the building.\n\
- **`Bathroom` and `Balcony` contain `\"> 10\"`,** which becomes 11: it preserves the ordering without inventing a precise value.\n\
- **`Car Parking` is `\"1 Covered\"`, `\"2 Open\"`, and sometimes `\"1 Covered,\"`** with a trailing comma. Split into a count and a `covered` flag.\n\
- **`overlooking` is a set, not a category.** `\"Garden/Park, Pool, Main Road\"` in inconsistent orders makes 20 distinct strings out of 3 facts, so it becomes three binary features instead of a 20-way one-hot.\n\
- **`facing` spells one direction two ways** (`\"South - West\"` and `\"South -West\"`); punctuation and spaces are stripped before encoding.\n\
- **Missing values become their own category.** Blank `facing` and blank `Ownership` are 37% and 35% of the file - too many to drop, and their absence is plausibly informative, so they encode as `missing` rather than being imputed away.\n\n",
            thousands(self.cleaning.no_price),
            thousands(self.cleaning.no_area)
        );

        let _ = write!(
            s,
            "**`Society` is dropped, and this is the measurement behind that.** It has {} distinct values and is 58% blank. The 50 most common societies together cover only {:.1}% of rows, so a top-50-plus-`other` encoding would put ~{:.0}% of listings in the catch-all bucket and buy 50 columns of almost pure noise. `location` gets the top-N treatment; `Society` is not worth its dimensions.\n\n\
**Outliers.** Price per square foot was computed for every row, and the tails past the 1st and 99th percentile trimmed: everything kept prices between {:.0} and {:.0} rupees/sqft. That removed {} rows.\n\n",
            self.society.distinct,
            self.society.top50_coverage_pct,
            100.0 - self.society.top50_coverage_pct,
            self.cleaning.ppsf_low,
            self.cleaning.ppsf_high,
            thousands(self.cleaning.outliers)
        );

        // -- 3 ---------------------------------------------------------------
        let _ = write!(
            s,
            "## 3. Exploratory data analysis\n\n### Price is heavily skewed\n\n![Price distribution](01_price_distribution.svg)\n\n\
The median listing is **{}**, the middle half runs {} to {}, and the 1st and 99th percentiles are {} and {}. The mean is {:.2}x the median - that ratio *is* the skew. On a linear axis this chart is one bar against the y axis; on a log axis it is close to symmetric, which is the entire argument for training on log price.\n\n",
            rupees(q[2]),
            rupees(q[1]),
            rupees(q[3]),
            rupees(q[0]),
            rupees(q[4]),
            self.facts.price_skew_ratio
        );

        let _ = write!(
            s,
            "### Price against area\n\n![Price vs area](02_price_vs_area.svg)\n\n\
Log area and log price correlate at **r = {:.3}**. A straight line on a log-log plot is a power law, so area enters the model as `log(area)` rather than raw square feet. The vertical banding is real: listings cluster on round numbers like 1000 and 1200 sqft. Both scatter charts draw an evenly spaced 12,000-listing sample - plotting every row makes a 4 MB file and no clearer a picture - but their axis limits come from the full data.\n\n\
### Where the listings are\n\n![Median price by city](03_price_by_location.svg)\n\n| city | listings | median price |\n|---|---|---|\n",
            self.facts.log_area_price_corr
        );
        for g in &self.facts.top_locations {
            let _ = writeln!(
                s,
                "| {} | {} | {} |",
                g.label,
                thousands(g.count),
                rupees(g.median)
            );
        }
        let dearest = self
            .facts
            .top_locations
            .iter()
            .max_by(|a, b| a.median.total_cmp(&b.median));
        let cheapest = self
            .facts
            .top_locations
            .iter()
            .min_by(|a, b| a.median.total_cmp(&b.median));
        if let (Some(d), Some(c)) = (dearest, cheapest) {
            let _ = write!(
                s,
                "\nAmong the busiest cities the median ranges from {} in {} to {} in {} - a **{:.1}x spread** on location alone, which is why city is the largest block of one-hot columns in the model.\n\n",
                rupees(c.median),
                c.label,
                rupees(d.median),
                d.label,
                d.median / c.median
            );
        }

        s.push_str("### Furnishing and bathrooms\n\n![Price by furnishing](04_price_by_furnishing.svg)\n\n");
        for g in &self.facts.by_furnishing {
            let _ = writeln!(
                s,
                "- `{}`: {} listings, median {}",
                g.label,
                thousands(g.count),
                rupees(g.median)
            );
        }
        s.push_str("\nThe boxes overlap heavily, so furnishing shifts the price but nowhere near decides it - useful as a feature, useless on its own.\n\n![Price by bathroom count](05_price_by_bathroom.svg)\n\n");
        for g in &self.facts.by_bathroom {
            let _ = writeln!(
                s,
                "- {} bathrooms: {} listings, median {}",
                g.label,
                thousands(g.count),
                rupees(g.median)
            );
        }
        let _ = write!(
            s,
            "\nBathroom count separates the groups far more cleanly than furnishing does. It is a proxy for size and segment at once, which is why it survives as a feature despite correlating with area.\n\n\
### Price per square foot\n\n![Price per sqft](06_price_per_sqft.svg)\n\n\
After trimming, the median rate is **{:.0} rupees/sqft**. This is also the quantity the outlier filter is built on.\n\n",
            self.facts.median_ppsf
        );

        // -- 4 ---------------------------------------------------------------
        let _ = write!(
            s,
            "## 4. Features and split\n\n\
{} kept rows are shuffled with a fixed seed and split **{} train / {} validation / {} test**. The shuffle matters because the file is sorted by city. Taking the last 20% would test on cities the model never trained on.\n\n\
The scaler statistics, the imputation medians and the one-hot vocabularies are all fitted on the training split alone. Fitting them on everything would leak test data into the preprocessing and inflate every number below.\n\n\
The encoded vector is **{} features**: {} numeric (standardised, missing values imputed with the training median) followed by one-hot blocks.\n\n| block | columns |\n|---|---|\n| numeric | {} |\n",
            thousands(kept),
            thousands(self.train_rows),
            thousands(self.val_rows),
            thousands(self.test_rows),
            self.spec.input_dim(),
            self.spec.numeric.len(),
            self.spec.numeric.len()
        );
        for c in &self.spec.categorical {
            let _ = writeln!(s, "| `{}` one-hot | {} |", c.name, c.vocab.len());
        }
        s.push_str("\nEvery one-hot block ends with an `other` column, so a city the model never saw still encodes fine instead of failing or shifting all the later columns along by one.\n\n");

        // -- 5 ---------------------------------------------------------------
        s.push_str("## 5. Models\n\nAll three are trained with Vearo: mini-batch AdamW, batch 512, warmup plus cosine decay, MSE loss, and the epoch with the best validation loss is the one kept. The test split is scored exactly once, at the end.\n\n| model | shape | parameters | best epoch | device | time | MAE | RMSE | R2 | MdAPE |\n|---|---|---|---|---|---|---|---|---|---|\n");
        for r in &self.runs {
            let shape: Vec<String> = r.layer_dims.iter().map(ToString::to_string).collect();
            let _ = writeln!(
                s,
                "| {} | {} | {} | {} | {} | {:.0}s | {} | {} | {:.3} | {:.1}% |",
                r.name,
                shape.join("-"),
                thousands(r.params),
                r.best_epoch,
                r.device,
                r.seconds,
                rupees(r.test.mae),
                rupees(r.test.rmse),
                r.test.r2,
                r.test.mdape
            );
        }
        let _ = writeln!(
            s,
            "| *Rate card (city median rate x area)* | *no model* | *0* | *-* | *-* | *-* | {} | {} | {:.3} | {:.1}% |",
            rupees(self.baseline.mae),
            rupees(self.baseline.rmse),
            self.baseline.r2,
            self.baseline.mdape
        );

        s.push_str("\nMAE, RMSE and R2 are in rupees on the test set. **MdAPE** is the median absolute percentage error and it's the one to look at. Prices cover two orders of magnitude, so an MAE in rupees is dominated by a few very expensive listings. MdAPE tells you how wrong a normal prediction is.\n\n");

        let log_run = self
            .runs
            .iter()
            .find(|r| r.name.contains("MLP") && r.name.contains("log"));
        let raw_run = self.runs.iter().find(|r| r.name.contains("raw"));
        if let (Some(l), Some(r)) = (log_run, raw_run) {
            let _ = write!(
                s,
                "**Log target vs raw target.** The same network, same seed, same schedule, differing only in whether it predicts `ln(1 + price)` or the price itself (both standardised, so this compares the modelling choice and not float precision): MdAPE {:.1}% on the log target against {:.1}%, and R2 {:.3} against {:.3}. Squared error on raw rupees is dominated by the expensive tail, so the raw model buys accuracy on mansions with accuracy on everything else. The log target is the one exported.\n\n",
                l.test.mdape, r.test.mdape, l.test.r2, r.test.r2
            );
        }

        let winner_run = self.runs.iter().find(|r| r.name == self.winner);
        if let Some(w) = winner_run {
            let _ = write!(
                s,
                "### What de-duplication was worth\n\n\
The same architecture, trained and scored on the file exactly as it ships, with the 64% of duplicate rows left in:\n\n\
| test split | MdAPE | R2 |\n|---|---|---|\n\
| duplicates left in | {:.1}% | {:.3} |\n\
| de-duplicated (this project) | {:.1}% | {:.3} |\n\n\
The first row is the nicer number and the useless one. Most of its test listings are also in its training set, so the model is just recalling prices it has already seen. The second row is what it does on listings it has actually never seen, and that's the number used everywhere else here.\n\n",
                self.leaky.test.mdape, self.leaky.test.r2, w.test.mdape, w.test.r2
            );
        }

        s.push_str("### Predicted vs actual\n\n![Predicted vs actual](07_predicted_vs_actual.svg)\n\nBoth axes are log rupees and the dashed line is a perfect prediction. The points sit close to the diagonal through the middle and flatten out at both ends, which is the model pulling extremes toward the average. Squared error loss does that.\n\n### Training curves\n\n![Training curves](08_training_curves.svg)\n\nValidation loss follows training loss instead of turning back up, so the exported model isn't overfitted. The gap between the lines is how much it memorised.\n\n");

        if let Some(folds) = &self.cv {
            let n = folds.len() as f64;
            let mean_r2 = folds.iter().map(|m| m.r2).sum::<f64>() / n;
            let mean_mdape = folds.iter().map(|m| m.mdape).sum::<f64>() / n;
            let sd = (folds.iter().map(|m| (m.r2 - mean_r2).powi(2)).sum::<f64>() / n).sqrt();
            s.push_str(
                "### Bonus: 5-fold cross-validation\n\n| fold | R2 | MdAPE |\n|---|---|---|\n",
            );
            for (i, m) in folds.iter().enumerate() {
                let _ = writeln!(s, "| {i} | {:.3} | {:.1}% |", m.r2, m.mdape);
            }
            let _ = write!(
                s,
                "| **mean** | **{mean_r2:.3}** (sd {sd:.3}) | **{mean_mdape:.1}%** |\n\nThe spread across folds is small, so the single test-set number above is not a lucky split.\n\n"
            );
        }

        // -- 6 ---------------------------------------------------------------
        if let Some(w) = winner_run {
            let _ = write!(
                s,
                "### Is this model any good?\n\nThree reference points, all on the same held-out test split:\n\n| | MdAPE | R2 | what it knows |\n|---|---|---|---|\n| Rate card | {:.1}% | {:.3} | city and area, no model |\n| Linear regression | {:.1}% | {:.3} | all 89 engineered features, no interactions |\n| MLP | {:.1}% | {:.3} | the same features, with interactions |\n\n**Yes, relative to what it is given.** The rate card is what an agent does on the back of an envelope, and the network cuts its typical error by {:.0}% relative ({:.1}% to {:.1}%) while lifting R2 from {:.3} to {:.3}. Roughly half of that gain is the cleaning and encoding - the linear model on the same features already reaches {:.1}% - and the other half is interactions the linear model cannot express, such as an extra bathroom being worth more in Mumbai than in Jaipur.\n\n**No, in absolute terms, and the data is the reason.** A typical prediction is still {:.1}% out, which is too loose to price a specific flat. The ceiling is `location`: it is a *city*, and in Indian property the neighbourhood dominates. Two 1,000 sqft flats in Mumbai can differ threefold between Bandra and Bhiwandi, and nothing in the 89 features distinguishes them - so that variance is simply unlearnable here. The rate card's {:.1}% is a direct measurement of how much price variation city-plus-area leaves unexplained, and no model on these columns escapes much more of it than this one already does.\n\nThe locality is not missing from the file, though - it is sitting in `Title` (\"for sale in Punjabi Bagh East\") and `Description`, both currently unused. Parsing locality and BHK count out of that text is where the next real gain is, and it is a text-parsing problem rather than a modelling one.\n\n",
                self.baseline.mdape,
                self.baseline.r2,
                self.runs
                    .iter()
                    .find(|r| r.name.starts_with("Linear"))
                    .map_or(0.0, |l| l.test.mdape),
                self.runs
                    .iter()
                    .find(|r| r.name.starts_with("Linear"))
                    .map_or(0.0, |l| l.test.r2),
                w.test.mdape,
                w.test.r2,
                100.0 * (self.baseline.mdape - w.test.mdape) / self.baseline.mdape,
                self.baseline.mdape,
                w.test.mdape,
                self.baseline.r2,
                w.test.r2,
                self.runs
                    .iter()
                    .find(|r| r.name.starts_with("Linear"))
                    .map_or(0.0, |l| l.test.mdape),
                w.test.mdape,
                self.baseline.mdape
            );
        }

        let _ = write!(
            s,
            "## 6. Conclusion and export\n\n**{} is the exported model.** ",
            self.winner
        );
        let linear_run = self.runs.iter().find(|r| r.name.starts_with("Linear"));
        if let (Some(m), Some(l)) = (winner_run, linear_run)
            && m.name != l.name
        {
            {
                let _ = write!(
                    s,
                    "It beats the linear baseline on every metric - MdAPE {:.1}% against {:.1}%, R2 {:.3} against {:.3} - and the margin is worth the extra {} parameters. The baseline matters as much as the winner: a linear model on the same features reaches R2 {:.3}, so a good share of the signal is in the cleaning and the encoding, and the network adds the interactions on top - the fact that another bathroom is worth more in Mumbai than in Jaipur.\n\n",
                    m.test.mdape,
                    l.test.mdape,
                    m.test.r2,
                    l.test.r2,
                    m.params.saturating_sub(l.params),
                    l.test.r2
                );
            }
        }
        let _ = write!(
            s,
            "Three files are written to `models/`:\n\n\
- `house_price.ve` - the weights, in Vearo's checkpoint format.\n\
- `preprocess.json` - the feature spec: column order, imputation medians, scaler statistics, one-hot vocabularies, the target transform and the layer widths. The API loads this and calls the *same* encoder this pipeline used, from the shared `hp-core` crate, so training and serving cannot drift apart.\n\
- `locations.json` - the cities the model has a column for, which populates the frontend dropdown.\n\n\
After exporting, the pipeline builds a fresh network, loads the checkpoint into it, and asserts it reproduces a prediction to within 1e-6 - the equivalent of reloading a pickle before trusting it.\n\n\
### What would improve this next\n\n\
- `Title` and `Description` are free text holding the BHK count, which is currently unused; parsing bedrooms out of the title is likely the single biggest remaining gain.\n\
- Both area columns are blank on only {} rows, so imputing area would buy almost nothing - but 43% of listings have no *carpet* area and fall back to super area, and modelling the ratio between the two would sharpen those.\n\
- The `other` city bucket is a blunt instrument. With a proper geographic hierarchy (state, then city) an unseen city could inherit its state's price level.\n\
- De-duplication is exact-match. Two copies of one advertisement that differ by a single rounded square foot still both survive, so the real duplicate count is a floor, not a ceiling.\n",
            thousands(self.cleaning.no_area)
        );

        s
    }
}
